let data=[{name:"RajeshKumar",
            batch:"B45WD",
            gender:"Male",
            qualification:"BSC"},
            {name:"Anitha",
            batch:"B45WD",
            gender:"Female",
            qualification:"B.Com"},
            {name:"Prabhu",
            batch:"B45WD",
            gender:"Male",
            qualification:"BSC"},
            {name:"Soosana",
            batch:"B45WD",
            gender:"Female",
            qualification:"BBA"},
            {name:"Raghul",
            batch:"B45WD",
            gender:"Male",
            qualification:"BCA"},
            {name:"Vishnu",
            batch:"B45WD",
            gender:"Male",
            qualification:"BBA"},
            {name:"Porko",
            batch:"B45WD",
            gender:"Male",
            qualification:"B.Tech"}]
            
export default data;